export default {
  name: "pageBooking",
  title: "Pagina Programări",
  type: "document",
  fields: [
    { name: "heroTitle", title: "Titlu principal", type: "text", rows: 2 },
    { name: "heroLead", title: "Text introductiv", type: "text", rows: 3 },
    { name: "stepsTitle", title: "Secțiunea „Cum funcționează” — titlu", type: "string" },
    {
      name: "stepsSubtitle",
      title: "Secțiunea „Cum funcționează” — subtitlu",
      type: "text",
      rows: 2,
    },
    {
      name: "steps",
      title: "Pașii programării",
      type: "array",
      of: [{ type: "step" }],
    },
    { name: "locationsTitle", title: "Secțiunea cu hărți — titlu", type: "string" },
    {
      name: "locationsSubtitle",
      title: "Secțiunea cu hărți — subtitlu",
      type: "text",
      rows: 2,
      description: "Adresele și hărțile se editează la „Cabinete”.",
    },
    {
      name: "whatsappNote",
      title: "Nota de sub butonul de WhatsApp",
      type: "text",
      rows: 2,
    },
    { name: "contactTitle", title: "Cardul de contact — titlu", type: "string" },
    { name: "contactPhoneLabel", title: "Cardul de contact — eticheta „telefon”", type: "string" },
    { name: "contactEmailLabel", title: "Cardul de contact — eticheta „e-mail”", type: "string" },
    { name: "contactHoursLabel", title: "Cardul de contact — eticheta „program”", type: "string" },
    {
      name: "cabinetLabel",
      title: "Cuvântul dinaintea orașului",
      type: "string",
      description:
        "Apare ca „Cabinet Constanța”, pe cardul cu hartă și în datele de contact.",
    },
    { name: "mapLinkLabel", title: "Butonul „vezi pe hartă”", type: "string" },
    { name: "directionsLinkLabel", title: "Butonul „traseu”", type: "string" },

    {
      name: "optionalNote",
      title: "Mențiunea pentru câmpuri opționale",
      type: "string",
      description: "Apare lângă etichetele câmpurilor opționale. Ex: „(opțional)”.",
    },
    { name: "serviceLabel", title: "Eticheta câmpului „serviciu”", type: "string" },
    {
      name: "serviceUnknownOption",
      title: "Opțiunea „nu sunt sigur”",
      type: "string",
      description: "Prima opțiune din lista de servicii.",
    },
    { name: "nameLabel", title: "Eticheta câmpului „nume”", type: "string" },
    { name: "namePlaceholder", title: "Textul gri din câmpul „nume”", type: "string" },
    { name: "modalityLabel", title: "Eticheta „modalitate”", type: "string" },
    {
      name: "modalities",
      title: "Opțiuni de modalitate",
      type: "array",
      of: [{ type: "string" }],
      description: "Prima opțiune e selectată implicit. Ex: La cabinet, Online.",
    },
    { name: "intervalLabel", title: "Eticheta „interval orar”", type: "string" },
    {
      name: "intervals",
      title: "Opțiuni de interval orar",
      type: "array",
      of: [{ type: "string" }],
      description: "Ultima opțiune e selectată implicit (cea mai permisivă).",
    },
    { name: "detailsLabel", title: "Eticheta câmpului „detalii”", type: "string" },
    {
      name: "detailsPlaceholder",
      title: "Textul gri din câmpul „detalii”",
      type: "text",
      rows: 2,
    },
    {
      name: "previewTitle",
      title: "Titlul casetei cu previzualizarea mesajului",
      type: "string",
    },
    { name: "sendLabel", title: "Butonul de trimitere", type: "string" },

    { name: "message", title: "Mesajul trimis pe WhatsApp", type: "whatsappMessage" },
    { name: "seo", title: "Google și titlul din tab", type: "seo" },
  ],
  preview: { prepare: () => ({ title: "Pagina Programări" }) },
};
